### PR TITLE
chore(deps): simplify dep management across dev environments

### PR DESCRIPTION
**Pull request by varl**
Make it easier to manage dependencies across multiple dev environments,
while maintaining the original setup_venv script functionality.

Dependency installation and setup is extracted to scripts/setup-deps.sh,
and the setup_venv script has been refactored to use it. This split
allows us to use venv, virtualenv, or Docker with the docs-builder.

Instead of using setuputils, we use pip to install the local plugins in
development mode (safer alternative to 'setup.py develop') which is
equivalent but is able to manage the dependencies with pip.

Calls to the 'pip' binary has been replaced with 'pip3' to ensure that
we use a python3 compatible pip version.

"Temporary hacks" may not be necessary when using pip3 to install the
deps, but has been maintained because I cannot verify this locally on
account of not being able to use venv.

Finally the README has been updated with additional prerequisites for
docs-builder to work (cairo and pango).

### CODE REVIEW

**Comment by Philip-Larsen-Donnelly** [comment]
The "Temporary Hacks" are necessary as they are direct patches to the python-markdown source code, in order to achieve some of the behaviour we want. It will take a bit of effort to convert them into independent extensions.

**Comment by Philip-Larsen-Donnelly** [comment]
I thought cairo and pango were pulled in as dependencies to the requirements!? At least, they were for me (and are on gitHub Actions, I believe).

**Comment by varl** [comment]
> I thought cairo and pango were pulled in as dependencies to the requirements!? At least, they were for me (and are on gitHub Actions, I believe).

I'm talking about the OS level requirements (maybe prerequisites is a better term) in the README. Pango and Cairo are system-level libraries, and not pure Python dependencies. There are Python bindings to those libraries that pip can install, but pip cannot guarantee that the libraries exist in the operating system.

For example on Debian, Cairo and Pango aren't installed by default, which is provable as I set this up to run in Docker on a clean image to avoid any interactions with my system level packages, and it doesn't work without installing these: https://github.com/varl/images/blob/master/python/docs-builder/Dockerfile#L5-L6

Ubuntu installs Pango and Cairo by default, and GitHub images are based on Ubuntu, so that's probably why it works OK there.

**Comment by varl** [comment]
> The "Temporary Hacks" are necessary as they are direct patches to the python-markdown source code, in order to achieve some of the behaviour we want. It will take a bit of effort to convert them into independent extensions.

Alright, what behavior changes am I looking for with those patches ?

I would like to see if it works as expected in my environment. Would I get errors if it didn't work or is it the end result that's a bit different ?

**Comment by Philip-Larsen-Donnelly** [comment]
I think it's just the end result that's different - basically supporting certain markdown extensions in a way that suits our needs.
I'll need to have a look to remind myself (and add some notes about why the hacks are there).

**Comment by Philip-Larsen-Donnelly** [comment]
> > I thought cairo and pango were pulled in as dependencies to the requirements!? At least, they were for me (and are on gitHub Actions, I believe).
> 
> I'm talking about the OS level requirements (maybe prerequisites is a better term) in the README. Pango and Cairo are system-level libraries, and not pure Python dependencies. There are Python bindings to those libraries that pip can install, but pip cannot guarantee that the libraries exist in the operating system.
> 
> For example on Debian, Cairo and Pango aren't installed by default, which is provable as I set this up to run in Docker on a clean image to avoid any interactions with my system level packages, and it doesn't work without installing these: https://github.com/varl/images/blob/master/python/docs-builder/Dockerfile#L5-L6
> 
> Ubuntu installs Pango and Cairo by default, and GitHub images are based on Ubuntu, so that's probably why it works OK there.

Right. This makes sense. I think that Cairo and Pango dependencies come from WeasyPrint, and seem to recall there are prerequisites on their website.

**Comment by varl** [comment]
## Regarding the "hacks"

`blockprocessors.py`: 

Original: https://github.com/Python-Markdown/markdown/blob/3.2.1/markdown/blockprocessors.py
Ours: https://github.com/dhis2/dhis2-docs-builder/blob/master/tools/python/blockprocessors.py

Our requirements file states that we depend on Markdown 3.2.1. After comparing the `blockprocessors.py` file from 3.2.1 with our modified version, I don't understand why we are applying this patched version. It seems quite out of date. It was added in ea354c18e89073619d131a6ff3dbdaf0302ae8df and has never been changed in this repo. I found it in added here in its entirety: https://github.com/dhis2/dhis2-docs/commit/4a96f079f7d7a57be2867d9a17e45007fdfeeaf6 but I cannot find where it came from originally.

`attr_list.py`: 

This is an official extension, that's bundled with Python-Markdown: https://python-markdown.github.io/extensions/attr_list

`tables.py`:

This is also an officially supported extension and available from the standard Python-Markdown library: https://python-markdown.github.io/extensions/tables/

It may be that they are not included in 3.2.1 of Python-Markdown, so we could update Python-Markdown to 3.3.4 and remove some of these hacks it seems.

**Comment by Philip-Larsen-Donnelly** [comment]
No. The hacks all do some small things slightly differently from the official library/extension. (E.g. the tables extension has a tweak to support captions in our implementation).

Basically, I should put all of those tweaks into a custom extension _then_ we can remove the hacks. I looked through them recently and it shouldn't be too difficult.

**Comment by varl** [comment]
> Basically, I should put all of those tweaks into a custom extension _then_ we can remove the hacks. I looked through them recently and it shouldn't be too difficult.

Alright.

**Comment by varl** [comment]
Either way, the hacks are maintained in this PR, so does that mean we can merge it ?

**Comment by varl** [comment]
Actually, never mind, I can workaround it in my image.

**Comment by Philip-Larsen-Donnelly** [comment]
@varl  I'm not against merging this PR.

**Review by Philip-Larsen-Donnelly — APPROVED** [review]

**Pull request merged**
